<?php if (count($errors)>0) : ?>

<ul class ="alert alert-danger"> 
    <?php foreach($errors as $e) : ?>
        <li><?= $e ?></li>
    <?php endforeach;?>  
</ul>
    <?php endif;?>


<form action="" method="POST">
    <div class="form-group">
        <label for="firstname">Prénom :</label>
        <input type="text"  class="form-control" id="firstname" value="<?= $prenom ?>" name="firstname">
    </div>
    <div class="form-group">
        <label for="lastname">Nom :</label>
        <input type="text"  class="form-control" id="lastname" value="<?= $lastname ?>" name="lastname">
    </div>
    <div class="form-group">
        <label for="email">Email :</label>
        <input type="text" class="form-control" id="email"value="<?= $email ?>" name="email">
    </div>
    <div class="form-group">
        <label for="phone">Téléphone :</label>
        <input type="text"  class="form-control" id="phone"value="<?= $phone ?>" name="phone">
    </div>
    <button type="submit">Sauvegarder</button>
</form>