<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
     <div class="container">
        <h1>Contact</h1>
        <?php include 'form.phtml';?>
        <br>
        <?php include 'list.phtml';?>
     
     </div>
    
   
</body>
</html>